<?php
require_once(__DIR__.'/../vendor/autoload.php');

use App\Models\Pessoa;
use App\Models\Motor;
use App\Models\Veiculo;
use App\Models\Carro;
$p = new Pessoa();

print ("<br> Desenvolvendo Carros no PHP puro... <br>");
$c1 = new Carro();
$c1->setnome("Fusca");
$c1->setmarca("Volkswagen");
$c1->setcor("preto");
$c1->setano("1975");
$c1->setmotor("MotorFusca");
print ("<br>" . $c1->getmarca() . " " . $c1->getnome() . " " . $c1->getcor() . " " . $c1->getano() . ": " . $c1->acelerar());

$c2 = new Carro();
$c2->setnome("Celta");
$c2->setmarca("Chevrolet");
$c2->setcor("1995");
$c2->setano("Azul");
$c2->setmotor("MotorCelta");
print ("<br>" . $c2->getmarca() . " " . $c2->getnome() . " " . $c2->getcor() . " " . $c2->getano() . ": " . $c2->acelerar());
$c3 = new Carro();
$c3->setnome("Camaro");
$c3->setmarca("Chevrolet");
$c3->setcor("2006");
$c3->setano("Amarelo");
$c3->setmotor("MotorCamaro");
print ("<br>" . $c3->getmarca() . " " . $c3->getnome() . " " . $c3->getcor() . " " . $c3->getano() . ": " . $c3->acelerar());
$c4 = new Carro();
$c4->setnome("Ka");
$c4->setmarca("Ford");
$c4->setcor("2001");
$c4->setano("Verde");
$c4->setmotor("MotorFordKa");
print ("<br>" . $c4->getmarca() . " " . $c4->getnome() . " " . $c4->getcor() . " " . $c4->getano() . ": " . $c4->acelerar());
$c5 = new Carro();
$c5->setnome("Berlinetta");
$c5->setmarca("Ferrari");
$c5->setcor("2008");
$c5->setano("Vermelho");
$c5->setmotor("MotorFerrari");
print ("<br>" . $c5->getmarca() . " " . $c5->getnome() . " " . $c5->getcor() . " " . $c5->getano() . ": " . $c5->acelerar());
$c6 = new Carro();
$c6->setnome("Huracan");
$c6->setmarca("Lamborghini");
$c6->setcor("2017");
$c6->setano("Vermelho");
$c6->setmotor("MotorLamborghini");
print ("<br>" . $c6->getmarca() . " " . $c6->getnome() . " " . $c6->getcor() . " " . $c6->getano() . ": " . $c6->acelerar());
